// Export selected default bags
export const defaultBags = [
  {
    id: 1,
    attributes: [
      "Bohiya",
      '"Okegawa Dou (dō) guskou',
      "Hoshi-bachi kabuto",
      "Hakama of Kiyohara clan",
      "Shino Odatsugi of Rokkaku clan",
      '"Water Sand" Sashimono of Kikkawa clan +1',
      "Bronze Ring",
    ],
  },
  {
    id: 111,
    attributes: [
      "Ring Mail of Giants",
      "Demonhide Boots of the Fox",
      "Heavy Gloves",
      "Cap",
      "Necklace",
      "Gold Ring",
      "Wool Sash of Protection",
      "Ghost Wand",
    ],
  },
  {
    id: 420,
    attributes: [
      "Chain Mail",
      "Shoes of Enlightenment",
      "Demon's Hands",
      "Ancient Helm",
      "Necklace",
      "Platinum Ring of Vitriol",
      "Heavy Belt",
      '"Honour Grasp" Katana of Protection +1',
    ],
  },
  {
    id: 6969,
    attributes: [
      "Chain Mail",
      "Holy Greaves of Giants",
      "Silk Gloves",
      "Dragon's Crown",
      "Pendant of Perfection",
      "Titanium Ring of Giants",
      "Heavy Belt",
      "Bone Wand",
    ],
  },
  {
    id: 1234,
    attributes: [
      "Holy Chestplate",
      "Divine Slippers of Perfection",
      "Dragonskin Gloves",
      '"Woe Shout" Demon Crown of Protection +1',
      "Necklace",
      "Titanium Ring",
      "Silk Sash",
      "Book",
    ],
  },
  {
    id: 1337,
    attributes: [
      "Divine Robe",
      '"Foe Peak" Shoes of Reflection +1',
      "Divine Gloves",
      "Full Helm",
      "Necklace",
      "Titanium Ring",
      "Ornate Belt",
      "Falchion of Reflection",
    ],
  },
  {
    id: 6969,
    attributes: [
      "Chain Mail",
      "Holy Greaves of Giants",
      "Silk Gloves",
      "Dragon's Crown",
      "Pendant of Perfection",
      "Titanium Ring of Giants",
      "Heavy Belt",
      "Bone Wand",
    ],
  },
];
