// Export selected default bags
export const defaultBags = [
  {
    id: 1,
    attributes: [
      "Bohiya",
      '"Okegawa Dou (dō) guskou',
      "Hoshi-bachi kabuto",
      "Hakama of Kiyohara clan",
      "Shino Odatsugi of Rokkaku clan",
      '"Water Sand" Sashimono of Kikkawa clan +1',
      "Bronze Ring",
    ],
  },
  {
    id: 8000,
    attributes: [
      '"Time Ruby" Yawara of Kamo Clan',
      "Temeshi-gusoku",
      '"Moon Mithril" Tatami kabutoi of Kone Family +1',
      "Kaku Obi",
      "Mid Edo Kegustsu",
      "Sashinuki kote",
      '"Fire Bone" Tessen of Inaba clan',
      "Ruby Ring",
    ],
  },
  {
    id: 2543,
    attributes: [
      "Tenegashima of Kiyohara clan",
      "Kusari Gusoku Of Toki clan",
      '"Shadow Sapphire" Zunari kabuto Of Oda clan ',
      "Katana Obi",
      "Geta of Yamachi clan",
      "Han Kote",
      "Suitou of Asukak family",
      'Jade Ring',
    ],
  },
  {
    id: 1017,
    attributes: [
      "Horokubiya",
      "Nanban dou (do) gusoku",
      "Kawari Kabuto",
      "Kaku Obi",
      "Kegutsu",
      "Kote Haramaki",
      "Tessen",
      '"Water Steel" Silver ring of Kusunoki Mesashige',
    ],
  },
  {
    id: 1818,
    attributes: [
      "Bohiya",
      "Dange dou (do) gusoku",
      "Tatami kabuto",
      'Hakama',
      "Slippers",
      "Leather Yugaka",
      "Meadate",
      "Gold Ring of Konoe family",
    ],
  },
  {
    id: 3333,
    attributes: [
      "Gunsen",
      'Munemenui dou (do)',
      "Za-boshi Kabuto",
      '"Water Wood" Uwa Obi Tomoe Gozen +1',
      "Kogake of Oda clan",
      "Happuri",
      "Meno",
      "Jade ring Of Kikkawa clan",
    ],
  },
  {
    id: 5555,
    attributes: [
      "Shuriken of Kusunoki Mesashige",
      "Yukata of Oda clan",
      "Hoshi-bachi kabuto",
      "Kaku Obi of ikoma clan",
      "Waraji",
      "Aigote of Nakatomi clan",
      "Tessen",
      "Ruby Ring of Tomoe Gozen",
    ],
  },
];
